# Builds a Docker image and pushes it to the Docker Hub registry.
name: Docker Image CI

on:
  workflow_dispatch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show working directory
        run: pwd && ls -la
    
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag demo-github-actions:$(date +%s)

      - name: Docker image list
        run: docker image ls
