# Builds a Docker image and stores it in a local Docker cache.
name: Docker Image Local Build

# on:
#   workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image TAG"
        # required: true
        type: string
        # default: $(date +%s)
        # default: $(date -u +"%F-%H%M%S")
        # default: $(date -u +"%F-%H%M%S-UTC")
        # default: 'latest'

#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: ghcr.io
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: demo-github-actions
  INPUT_TAG: ${{ github.event.inputs.tag }}
  # IMAGE_TAG: ${INPUT_TAG:-"latest"}
  # DATE: $(date +%s)
  # DATE: $(date -u +"%F-%H%M%S-UTC")
  # IMAGE_TAG: ${INPUT_TAG:-${DATE}}
  IMAGE_TAG: ${INPUT_TAG:-$(date -u +"%F-%H%M%S-UTC")}
  DOCKERFILE: Dockerfile
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show working directory
        run: pwd && ls -la

      - name: Show Docker image TAG to apply
        run: echo "${{ env.IMAGE_TAG }}"

      - name: Build the Docker image
        run: docker build . --file ${{ env.DOCKERFILE }} --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Docker image list
        run: docker image ls
