# Builds a Docker image and stores it in a local Docker cache.
name: Docker Image Local Build

on:
  workflow_dispatch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # Name of the Docker image with owner prefix, e.g. owner/image
  IMAGE_NAME: ivanenko/demo-github-actions
  # Location of Dockerfile (defaults to Dockerfile)
  DOCKERFILE: Dockerfile

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show working directory
        run: pwd && ls -la

      - name: Show Docker image IMAGE_NAME to apply
        run: echo "${{ env.IMAGE_NAME }}"

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME }}  # repo/image
          # tags: v1, latest
          # Auto-tagging with GitOps:
          # # Adds the 'latest' tag to the GitOps-generated tags
          addLatest: true
          # Suffixes a build timestamp to the branch-based Docker tag, e.g. main-1234567-2021-09-01.195027
          addTimestamp: true
          registry: ${{ env.REGISTRY }}
          dockerfile: ${{ env.DOCKERFILE }}
          # username: ${{ secrets.DOCKER_HUB_USERNAME }}
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker image list
        run: docker image ls
